### ISSUE TITLE
Problems with site on Lecture 5

### ISSUE THREAD

**Issue by otanavarro** [jamesjuett/eecs280-async-lectures#23]
I am working on lecture #5 (Part 2: const Conversion) and even though I already answered the question in the checkpoint, the site marks it as in progress instead of completed.
<img width="863" alt="Screenshot 2024-01-29 at 9 53 21 PM" src="https://github.com/jamesjuett/eecs280-async-lectures/assets/143959446/aa1f14cd-ab0b-40d5-948b-ccddd354529d">

**Comment by jamesjuett** [comment]
Thanks for filing this issue. In this case, your answer would need to specifically mention that it's the call to `red(arr1)` or include text something like "calling red on arr1" or "calling red on the first array".

However, I'm glad you pointed this out because I had made a mistake on the usual feedback icon such that it wasn't showing up for all answers that weren't getting credit, making it difficult to figure out why the question wasn't marking as completed.

I've added that feedback in e6f2bfe. (This might not show up for ~10 minutes since GitHub Pages allows browsers to cache assets for that amount of time. However, if you update your answer, it should meet the original completion criteria anyway.)
